name: Auto Assign PRs and Issues

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR or Issue
        uses: actions/github-script@v7
        with:
          script: |
            const isPR = !!context.payload.pull_request;

            if (isPR) {
              // Pull Request
              github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                assignees: ['29cmtruedamage', 'Paul-SE1', 'xP3rsy']
              });
            } else {
              // Issue
              github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                assignees: ['issue-user']
              });
            }
